services:
  - type: web
    name: neutral-news
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 120
    envVars:
      - key: NEWSAPI_ORG_KEY
        sync: false
      - key: GUARDIAN_API_KEY
        sync: false
      - key: AYLIEN_APP_ID
        sync: false
      - key: AYLIEN_API_KEY
        sync: false
      - key: GNEWS_API_KEY
        sync: false
      - key: NEWSAPI_AI_KEY
        sync: false
      - key: MEDIASTACK_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SHARECOUNT_API_KEY
        sync: false
      - key: NYT_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /test
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      cpu: 1x
      memory: 1024
      storage: 512 